version: "3.7"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini

  web:
    image: nginx:1.18-alpine
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    image: mysql:8.0.26
    build: ./infra/mysql
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      TZ: ${DB_TZ}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHP_MYADMIN_PORT}:80
    depends_on:
      - db

volumes:
  db-store:
